site_name: ACCESS-NRI - Training

# Git repository
repo_url: https://github.com/ACCESS-NRI/Training
repo_name: Training
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/


# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  logo: assets/ACCESSLogoJustPlanet.png

# Footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel

copyright: Copyright &copy; 2022 - ACCESS-NRI

extra_css:
  - css/fontello.css

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: 
    - index.md
    - License: LICENSE.md
  - How-tos:
    - Git and GitHub:
      - HowTos/GitAndGitHub/index.md
      - Basics: HowTos/GitAndGitHub/basics.md
      - Git setup: HowTos/GitAndGitHub/git_setup.md
      - GitHub setup: HowTos/GitAndGitHub/github_setup.md
